import { SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col font-[family-name:var(--font-geist-sans)]">
      <nav className="flex items-center justify-between px-8 py-4 border-b border-gray-200">
        <span className="text-xl font-bold">Oakbook</span>
        <div className="flex items-center gap-4">
          <SignedOut>
            <Link
              href="/sign-in"
              className="text-sm font-medium text-gray-600 hover:text-gray-900"
            >
              Sign in
            </Link>
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </div>
      </nav>

      <main className="flex-1 flex flex-col items-center justify-center px-8">
        <div className="max-w-2xl text-center space-y-6">
          <h1 className="text-5xl font-bold tracking-tight">
            Your YouTube Learning Companion
          </h1>
          <p className="text-lg text-gray-600">
            Chat with AI about any YouTube video. Get explanations, summaries,
            and deeper understanding — powered by context-aware AI.
          </p>

          <div className="flex justify-center gap-4 pt-4">
            <SignedOut>
              <Link
                href="/sign-up"
                className="px-6 py-3 rounded-md font-medium bg-gray-900 text-white hover:bg-gray-800 transition-colors"
              >
                Get Started
              </Link>
            </SignedOut>
            <SignedIn>
              <Link
                href="/dashboard"
                className="px-6 py-3 rounded-md font-medium bg-gray-900 text-white hover:bg-gray-800 transition-colors"
              >
                Go to Dashboard
              </Link>
            </SignedIn>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mt-20">
          <div className="text-center space-y-2">
            <h3 className="font-semibold text-lg">Video-Aware Chat</h3>
            <p className="text-sm text-gray-600">
              AI understands the video you&apos;re watching and answers questions
              in context.
            </p>
          </div>
          <div className="text-center space-y-2">
            <h3 className="font-semibold text-lg">Chrome Extension</h3>
            <p className="text-sm text-gray-600">
              One click from any YouTube video to start a learning conversation.
            </p>
          </div>
          <div className="text-center space-y-2">
            <h3 className="font-semibold text-lg">AI-Powered Insights</h3>
            <p className="text-sm text-gray-600">
              Get summaries, explanations, and follow-up questions generated by
              AI.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
